CREATE DATABASE IF NOT EXISTS cambridge_clone;
USE cambridge_clone;

CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(180) NOT NULL,
  type VARCHAR(80) NOT NULL,
  fit VARCHAR(80),
  colors INT DEFAULT 1,
  price DECIMAL(10, 2) NOT NULL,
  image TEXT NOT NULL,
  gallery JSON,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
